[package]
name = "bench_search_file"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "^1.39.2", features = ["full"] }
tokio-macros = "2.4.0"
tokio-util = "0.7.11"
chrono = "0.4.38"
lazy_static = "1.5.0"